   ;====================================================================
   ; Main.asm file generated by New Project wizard
   ;
   ; Created:   Fri Nov 22 2024
   ; Processor: 8086
   ; Compiler:  MASM32
   ;
   ; Before starting simulation set Internal Memory Size 
   ; in the 8086 model properties to 0x10000
   ;====================================================================

DATA SEGMENT
	    PORTA		    EQU	0F0h
	    PORTB		    EQU 0F2h
	    PORTC		    EQU 0F4h
	    COM_REG		    EQU 0F6h
	    
	    PORTA2		    EQU 0E0h
	    PORTB2		    EQU 0E2h
	    PORTC2		    EQU 0E4h
	    COM_REG2		EQU 0E6h
	    
	    PORTA3		    EQU 0C0h
	    PORTB3		    EQU 0C2h
	    PORTC3		    EQU 0C4h
	    COM_REG3		EQU 0C6h
	   
	    COMT			EQU 0D6h
	    
	    CLEAR		    DB	"                        ", "$"
	    SEC_START	    DB	"ENTER PASSWORD: ", "$"
	    
	    DENIED		    DB	"ACCESS DENIED", "$"
	    PASS			DB	"6452", "$"						;REVERSED
	    
	    AC_ON		    DB	"1 AC: ON ", "$"
	    AC_OFF		    DB	"1 AC: OFF ", "$"
	                
	    PO_ON		    DB	"2 POWER OUTLETS: ON ", "$"
	    PO_OFF		    DB	"2 POWER OUTLETS: OFF ", "$"
	    
	    LI_ON			DB	"3 LIGHTS: ON ", "$"
	    LI_OFF		    DB	"3 LIGHTS: OFF ", "$"
	    
	    SD_ALL		    DB	"4 SHUTDOWN ALL", "$"
	    
	    TMR 			DB 	"SET TIMER", "$"
	    CANCELLED 	    DB 	"ACTION STOPPED" , "$"
	    
	    OFF_PMT		    DB	"SHUTTING BRANCH DOWN", "$"
	    ON_PMT		    DB	"TURNING BRANCH ON", "$"
	    ALL_PMT		    DB	"ALL SHUTTING DOWN", "$"
	    
	    BACK			DB	"PRESS # TO GO BACK", "$"
	    PRESS			DB	"PRESS * TO ENTER", "$"
	    
	    MIN0 			DB 	"00 MINUTES", "$"
	    MIN1 			DB 	"01 MINUTE ", "$"
	    MIN2			DB 	"02 MINUTES", "$"
	    MIN3 			DB 	"03 MINUTES", "$"
	    MIN4 			DB 	"04 MINUTES", "$"
	    MIN5 			DB 	"05 MINUTES", "$"
	    MIN6 			DB 	"06 MINUTES", "$"
	    MIN7 			DB 	"07 MINUTES", "$"
	    MIN8 			DB 	"08 MINUTES", "$"
	    MIN9 			DB 	"09 MINUTES", "$"
	    
	    SEC			    DB	"A FEW SECONDS", "$"
	
	    TG_FLAG		    DB 	00h
	    MINS_FLAG 	    DB 	00h
	    
DATA ENDS

STK SEGMENT STACK
	 BOS DW 64d DUP(?)
	 TOS LABEL WORD
STK ENDS

CODE    SEGMENT PUBLIC "CODE"
	ASSUME CS:CODE, DS:DATA

START:
	    ; Set up data segment
	    MOV AX, DATA
	    MOV DS, AX
	    
	    ; Clear all registers
	    XOR AX, AX
	    XOR BX, BX
	    XOR CX, CX
	    XOR DX, DX
	    XOR SI, SI
	    XOR DI, DI
	    
;===========================Initialize device and LCD display=================================
	    INIT_DEVICES:
	      MOV DX, COM_REG
	      MOV AL, 89h				;CONTROL WORD FOR OUTPUT OUTPUT INPUT 8255
	      OUT DX, AL
	      
	      MOV DX, COM_REG2
	      MOV AL, 8Bh				;CONTROL WORD FOR OUTPUT INPUT INPUT 8255
	      OUT DX, AL
	      
	      MOV DX, COM_REG2
	      MOV AL, 89h				;CONTROL WORD FOR OUTPUT OUTPUT INPUT 8255
	      OUT DX, AL
	      
	      MOV DX, COMT
	      MOV AL, 37h				;CONTROL WORD FOR SQUARE WAVE GENERATOR 8253
	      OUT DX, AL
	      
	      ;TURN OFF ALL RELAYS
	      MOV DX, PORTA2
	      MOV AL, 00h
	      OUT DX, AL
	      
	      CALL INIT_LCD
	      
  ;==========================Security System Start========================================== 

	    ;START CODE HERE FOR SECURITY SYSTEM
	    
	    SEC_SYS_START:
	       CALL CLS
	       XOR CX, CX
	       
	       MOV AL, 080h
	       CALL INST_CTRL
	       
	       LEA SI, SEC_START
	       CALL PRINT_STRING
	       
	    CHECK_DAVBL:
	       MOV DX, PORTC
	       IN AL, DX
	       
	       TEST AL, 10h
	       JZ CHECK_DAVBL
	       
	       IN AL, DX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       AND AL, 0Fh
	       
	       CHECK_INPUT:
		  
		  CMP AL, 00h
		  JE SET_1
		  
		  CMP AL, 01h
		  JE SET_2
		  
		  CMP AL, 02h
		  JE SET_3
		  
		  CMP AL, 04h
		  JE SET_4
		  
		  CMP AL, 05h
		  JE SET_5
		  
		  CMP AL, 06h
		  JE SET_6
		  
		  CMP AL, 08h
		  JE SET_7
		  
		  CMP AL, 09h
		  JE SET_8
		  
		  CMP AL, 0Ah
		  JE SET_9
		  
		  CMP AL, 0Dh
		  JE SET_0
		  
		  JMP CHECK_DAVBL
		     
	   SET_1:
	       XOR BX, BX
	       MOV BL, '1'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_2:
	       XOR BX, BX
	       MOV BL, '2'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	    
	       JMP CHECK_DAVBL
	    
	    SET_3:
	       XOR BX, BX
	       MOV BL, '3'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_4:
	       XOR BX, BX
	       MOV BL, '4'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_5:
	       XOR BX, BX
	       MOV BL, '5'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_6:
	       XOR BX, BX
	       MOV BL, '6'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_7:
	       XOR BX, BX
	       MOV BL, '7'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_8:
	       XOR BX, BX
	       MOV BL, '8'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_9:
	       XOR BX, BX
	       MOV BL, '9'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL
	       
	    SET_0:
	       XOR BX, BX
	       MOV BL, '0'
	       
	       PUSH BX
	       
	       INC CX
	       
	       CMP CX, 04h
	       JE LOAD_PASS
	       
	       CALL PRINT_ASTERISK
	       
	       JMP CHECK_DAVBL

	 LOAD_PASS:
	       XOR AX, AX
	       XOR BX, BX
	       
	       LEA SI, PASS
	       
	       MOV CX, 04h
	       
	 CHECK_PASS:
	       MOV AL, [SI]
	       POP BX
	       
	       CMP AL, BL
	       JNE DENY
	       
	       INC SI
	       
	       LOOP CHECK_PASS
	       
	       JMP MENU_STARTUP
	       
	 DENY:
	       CALL CLS
	       
	       MOV AL, 080h
	       CALL INST_CTRL
	       LEA SI, DENIED
	       CALL PRINT_STRING
	       
	       MOV CX, 03h
	       
	       LOOP_3S:
	       CALL DELAY2
	       
	       LOOP LOOP_3S
	       
	       JMP SEC_SYS_START
;===========================POWER CONTROL SYSTEM================================================= 

	 ;START CODE HERE FOR POWER CONTROL SYSTEM
	    
	   MENU_STARTUP:
		  CALL CLS
		  
	    CHECK_STATUS_AC:
		  MOV DX, PORTB2
		  IN AL, DX
		  
		  AND AL, 001b
		  JNZ CHECK_AC_ON
		  
		  CALL AC_L
		  
		  JMP CHECK_STATUS_PO
		  
	    CHECK_STATUS_PO:
		  MOV DX, PORTB2
		  IN AL, DX
		  
		  AND AL, 010b
		  JNZ CHECK_PO_ON
		  
		  CALL PO_L
		  
		  JMP CHECK_STATUS_LI
		  
	    CHECK_STATUS_LI:
		  MOV DX, PORTB2
		  IN AL, DX
		  
		  AND AL, 100b
		  JNZ CHECK_LI_ON
		  
		  CALL LI_L
		  CALL SD
		  
		  JMP RELAY_CONTROL
	       
	    CHECK_AC_ON:
		  CALL AC_H
		  
		  JMP CHECK_STATUS_PO
		  
	    CHECK_PO_ON:
		  CALL PO_H
		  
		  JMP CHECK_STATUS_LI
		  
	    CHECK_LI_ON:
		  CALL LI_H
		  CALL SD
		  
		  JMP RELAY_CONTROL
	       
;===========================Relay Control System=========================================
        RELAY_CONTROL:	
	       MOV DX, PORTC
	       IN AL, DX
	       
	       TEST AL, 10h
	       JZ RELAY_CONTROL
	       
	       IN AL, DX
	       
	       AND AL, 0Fh

        CHECK_RELAY_INPUT:
	    CMP AL, 00h          ; Button 2 - AC Toggle
	    JE CHECK_AC_STATUS   ; If yes, jump to PO status check
    
	    CMP AL, 01h          ; Button 2 - PO Toggle
	    JE CHECK_PO_STATUS   ; If yes, jump to PO status check
    
	    CMP AL, 02h          ; Button 3 - LI Toggle
	    JE CHECK_LI_STATUS   ; If yes, jump to LI status check
	    
	    CMP AL, 04h          ; Button 4 - Shutdown Toggle
	    JE SHUTDOWN_ALL   ; If yes, jump to SD status check
	    
	    CMP AL, 0Eh	;button # - Go back/Lock system
	    JE SEC_SYS_START	;if yes, jump to security system start
	    
      JMP RELAY_CONTROL
	    
;==================CHECK CURRENT STATUS==================


;============================AC==================================
        CHECK_AC_STATUS:
            MOV DX, PORTB2
            IN AL, DX
	    
	    PUSH AX
	    
            AND AL, 01h
            JZ TURN_AC_ON
	    
            JMP TURN_AC_OFF
	    
      TURN_AC_ON:
	    MOV DX, PORTB2
	    IN AL, DX
	    
	    PUSH AX
	    
	    CALL CLS
	    MOV AL, 0C2h
	    CALL INST_CTRL
	    LEA SI, ON_PMT
	    CALL PRINT_STRING
	    
	    CALL DELAY_RELAY
	    
	    POP AX
		  
	    MOV DX, PORTA2
	    ADD AL, 001b
	    OUT DX, AL
	    
            JMP SEC_SYS_START
	    
        TURN_AC_OFF:
	    MOV SI, 0Fh
	    MOV AL, 001b
	    MOV [SI], AL
	    
	    JMP TIMER
	    
	    AC_OFF_NEXT:
		  MOV DX, PORTB2
		  IN AL, DX
		  
		  PUSH AX
		  
		  CALL CLS
		  
		  MOV AL, 0C0h
		  CALL INST_CTRL
		  LEA SI, OFF_PMT
		  CALL PRINT_STRING
		  
		  CALL DELAY_RELAY
		  
		  POP AX
		  
		  MOV DX, PORTA2
		  SUB AL, 001b
		  OUT DX, AL
		  
		  JMP SEC_SYS_START
	  
;============================POWER OUTLET==================================
      CHECK_PO_STATUS:
            MOV DX, PORTB2
            IN AL, DX
	    
	    PUSH AX
	    
            AND AL, 02h
            JZ TURN_PO_ON
	    
            JMP TURN_PO_OFF
	    
      TURN_PO_ON:
	    MOV DX, PORTB2
	    IN AL, DX
	    
	    PUSH AX
	    
	    CALL CLS
	    MOV AL, 0C2h
	    CALL INST_CTRL
	    LEA SI, ON_PMT
	    CALL PRINT_STRING
	    
	    CALL DELAY_RELAY
	    
	    POP AX
		  
	    MOV DX, PORTA2
	    ADD AL, 010b
	    OUT DX, AL
	    
            JMP SEC_SYS_START
	    
        TURN_PO_OFF:
	    MOV SI, 0Fh
	    MOV AL, 010b
	    MOV [SI], AL
	    
	    JMP TIMER
	    
	    PO_OFF_NEXT:
		  MOV DX, PORTB2
		  IN AL, DX
		  
		  PUSH AX
		  
		  CALL CLS
		  MOV AL, 0C0h
		  CALL INST_CTRL
		  LEA SI, OFF_PMT
		  CALL PRINT_STRING
		  
		  CALL DELAY_RELAY
		  
		  POP AX
		  
		  MOV DX, PORTA2
		  SUB AL, 010b
		  OUT DX, AL
		  
		  JMP SEC_SYS_START
	    
;==============================LIGHTS==================================
     CHECK_LI_STATUS:
            MOV DX, PORTB2
            IN AL, DX
	    
	    PUSH AX
	    
            AND AL, 04h
            JZ TURN_LI_ON
	    
            JMP TURN_LI_OFF
	    
      TURN_LI_ON:
	    MOV DX, PORTB2
	    IN AL, DX
	    
	    PUSH AX
	    
	    CALL CLS
	    MOV AL, 0C2h
	    CALL INST_CTRL
	    LEA SI, ON_PMT
	    CALL PRINT_STRING
	    
	    CALL DELAY_RELAY
	    
	    POP AX
		  
	    MOV DX, PORTA2
	    ADD AL, 100b        
	    OUT DX, AL
	    
            JMP SEC_SYS_START
	    
        TURN_LI_OFF:
	    MOV SI, 0Fh
	    MOV AL, 100b
	    MOV [SI], AL
	    
	    JMP TIMER
	    
	    LI_OFF_NEXT:
		  MOV DX, PORTB2
		  IN AL, DX
		  
		  PUSH AX
		  
		  CALL CLS
		  MOV AL, 0C0h
		  CALL INST_CTRL
		  LEA SI, OFF_PMT
		  CALL PRINT_STRING
		  
		  CALL DELAY_RELAY
		  
		  POP AX
		  
		  MOV DX, PORTA2
		  SUB AL, 0100b
		  OUT DX, AL
	    
            JMP SEC_SYS_START
	    
;==============================SHUTDOWN ALL==================================
	 SHUTDOWN_ALL:
	       MOV SI, 0Fh
	       MOV AL, 000b
	       MOV [SI], AL

	       JMP TIMER

	 SD_OFF_NEXT:
	       PUSH AX

	       CALL CLS
	       MOV AL, 0C2h
	       CALL INST_CTRL
	       LEA SI, ALL_PMT
	       CALL PRINT_STRING

	       CALL DELAY_RELAY

	       POP AX

	       MOV DX, PORTA2
	       MOV AL, 000b
	       OUT DX, AL

	       JMP SEC_SYS_START

;========================================================================
	 ALL_OFF:
	       CALL AC_L
	       CALL PO_L
	       CALL LI_L
	       CALL SD
	       
	 RET
	       
	 AC_L:
	       MOV AL, 080h
	       CALL INST_CTRL
	       LEA SI, AC_OFF
	       CALL PRINT_STRING
	       
	    RET
	       
	 AC_H:
	    MOV AL, 080h
	    CALL INST_CTRL
	    LEA SI, AC_ON
	    CALL PRINT_STRING
	    
	 RET
	    
	 PO_L:
	    MOV AL, 0C0h
	    CALL INST_CTRL
	    LEA SI, PO_OFF
	    CALL PRINT_STRING
	    
	    RET
	    
	 PO_H:
	    MOV AL, 0C0h
	    CALL INST_CTRL
	    LEA SI, PO_ON
	    CALL PRINT_STRING
	    
	    RET
	    
	 LI_L:
	    MOV AL, 094h
	    CALL INST_CTRL
	    LEA SI, LI_OFF
	    CALL PRINT_STRING
	    
	 RET
	    
	 LI_H:
	    MOV AL, 094h
	    CALL INST_CTRL
	    LEA SI, LI_ON
	    CALL PRINT_STRING
	    
	 RET

	 SD: 
	    MOV AL, 0D4h
	    CALL INST_CTRL
	    LEA SI, SD_ALL
	    CALL PRINT_STRING
	    
	 RET

;========================================================================
;TIMER
;========================================================================
	 TIMER:
	    CALL CLS

	    MOV AL, 085H
	    CALL  INST_CTRL

	    LEA SI, TMR
	    CALL PRINT_STRING

	    MOV AL, 0C5h
	    LEA SI, MIN0

	    CALL INST_CTRL
	    CALL PRINT_STRING

	    LEA SI, PRESS
	    MOV AL, 0D6h

	    CALL INST_CTRL
	    CALL PRINT_STRING

	    LEA SI, BACK
	    MOV AL, 095h

	    CALL INST_CTRL
	    CALL PRINT_STRING
	   
	    CHECK_TIMER:
		  MOV DX, PORTC
		  IN AL, DX
		  
		  TEST AL, 10H
		  
		  JZ CHECK_TIMER
		  IN AL, DX
		  
		  AND AL, 0FH
	    
	    CHECK_TIMER_INPUT:
		  CMP AL, 00H
		  JE M1
		  
		  CMP AL, 01H
		  JE M2
		  
		  CMP AL, 02H
		  JE M3
		  
		  CMP AL, 04H
		  JE M4
		  
		  CMP AL, 05H
		  JE M5
		  
		  CMP AL, 06H
		  JE M6
		  
		  CMP AL, 08H
		  JE M7
		  
		  CMP AL, 09H
		  JE M8
		  
		  CMP AL, 0AH
		  JE M9
		  
		  CMP AL, 0CH
		  JE TIMER_START
		  
		  CMP AL, 0Eh
		  JE MENU_STARTUP
		  
		  JMP CHECK_TIMER

	    M0:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN0 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    JMP CHECK_TIMER
		    
	    M1:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN1 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 1
		    
		    JMP CHECK_TIMER
		    
	    M2:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN2 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 2

		    JMP CHECK_TIMER
		    
	    M3:	
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN3 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 3
		    
		    JMP CHECK_TIMER
	    M4:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN4 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 4
		    JMP CHECK_TIMER
	    M5:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN5 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 5
		    JMP CHECK_TIMER

	    M6:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN6 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 6
		    
		    JMP CHECK_TIMER

	    M7:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN7 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 7
		    
		    JMP CHECK_TIMER

	    M8:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN8 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 8
		    
		    JMP CHECK_TIMER

	    M9:
		    MOV AL, 0C5h ; LOCATION WHERE TO START
		    
		    CALL  INST_CTRL ; SET LCD
		    LEA SI, MIN9 ; STRING LOAD TO SI
		    CALL PRINT_STRING ; DISPLAY STRING
		    
		    MOV MINS_FLAG, 9
		    
		    JMP CHECK_TIMER
		    
	    TIMER_START:
		      LEA SI, CLEAR
		      MOV AL, 095h
		     
		      CALL INST_CTRL
		      CALL PRINT_STRING
		      
		      CMP MINS_FLAG, 00h
		      JE SET_MIN0 
			
		     CMP MINS_FLAG, 01h
		     JE SET_MIN1	 

		     CMP MINS_FLAG, 02h
		     JE SET_MIN2	 
		     
		      CMP MINS_FLAG, 03h
		     JE SET_MIN3	 

		     CMP MINS_FLAG, 04h
		     JE SET_MIN4	 
		     
		     CMP MINS_FLAG, 05h
		     JE SET_MIN5	 

		     CMP MINS_FLAG, 06h
		     JE SET_MIN6	 
		     
		     CMP MINS_FLAG, 07h
		     JE SET_MIN7	 

		     CMP MINS_FLAG, 08h
		     JE SET_MIN8	 
		     
		     CMP MINS_FLAG, 09h
		     JE SET_MIN9
		     
		     SET_MIN0:
		     DEC MINS_FLAG
		     MOV AL, 0C1H ; LOCATION WHERE TO START
		     CALL  INST_CTRL ; SET LCD
		     
		     MOV SI, 0Fh
		     MOV AL, [SI]
		     
		     MOV BL, AL
		     MOV AL, BL
		     
		     CMP AL, 000b
		     JE SD_OFF_NEXT
		     
		     CMP AL, 001b
		     JE AC_OFF_NEXT
		     
		     CMP AL, 010b
		     JE PO_OFF_NEXT
		     
		     CMP AL, 100b
		     JE LI_OFF_NEXT
	    
	 SET_MIN1:
	    DEC MINS_FLAG
	    
	    MOV AL, 0C3h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD

	    LEA SI, SEC ; STRING LOAD TO SI
	    
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    CALL TIMER_SECONDS
	 
	 JMP TIMER_START

	 
	 SET_MIN2:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN1 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START
	 
	 SET_MIN3:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN2 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START
	 
	 SET_MIN4:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN3 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START
	 
	 SET_MIN5:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN4 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START

	 SET_MIN6:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN5 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START
	 
	 SET_MIN7:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN6 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START
	 
	 SET_MIN8:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN7 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START
	
	 SET_MIN9:
	    MOV AL, 0C5h ; LOCATION WHERE TO START
	    CALL  INST_CTRL ; SET LCD
	    
	    LEA SI, MIN8 ; STRING LOAD TO SI
	    CALL PRINT_STRING ; DISPLAY STRING
	    
	    DEC MINS_FLAG
	    
	    CALL TIMER_SECONDS
	    
	    JMP TIMER_START

	 TIMER_SECONDS:
		 MOV DX, 05h
		 
		 SEC_DELAY:
		     XOR AX, AX
		     
		     PUSH DX
		     
		     MOV DX, PORTC2
		     IN AL, DX
		     
		     CMP AL, 00h
		     JE CANCEL
		     
		     POP DX
		     
		     CALL DELAY
		     
		     DEC DX
		     CMP DX, 00h
		     
		     JE DONE
		     
		     JMP SEC_DELAY
		     
		 DONE:
		  
		  RET
		  
	 CANCEL:
		  CALL CLS
		  
		  MOV AL, 0C3h
		  CALL INST_CTRL
		  
		  LEA SI, CANCELLED
		  CALL PRINT_STRING
		  
		  CALL DELAY_RELAY
		  
		  CALL CLS
		  
		  JMP CHECK_STATUS_AC
	
;========================================================================
	PRINT_ASTERISK:
	    MOV AX, 02Ah
	    CALL DATA_CTRL
	    JMP DELAY_KEYPAD
	    
	RET
	
	CLS:
	   MOV AL, 080h
	    CALL INST_CTRL
	    LEA SI, CLEAR
	    CALL PRINT_STRING
	    
	    MOV AL, 0C0h
	    CALL INST_CTRL
	    LEA SI, CLEAR
	    CALL PRINT_STRING
	    
	    MOV AL, 094h
	    CALL INST_CTRL
	    LEA SI, CLEAR
	    CALL PRINT_STRING
	    
	    MOV AL, 0D0h
	    CALL INST_CTRL
	    LEA SI, CLEAR
	    CALL PRINT_STRING
	   
	RET
	
	PRINT_STRING:
	    MOV AX, [SI]
	    
	    CMP AL, "$"
	    JE DELAY1
	    
	    CALL DATA_CTRL
	    
	    INC SI
	    
	    JMP PRINT_STRING
	    
	 RET
	 
	 DELAY:
	    MOV CX, 0FFCh
	    
	    L3:
	       PUSH CX
	       
	       MOV CX, 10
	       
	    L2:
	       NOP
	       
	       LOOP L2
	       POP CX
	       
	       LOOP L3
	       
	    RET
	 
	DELAY1:
	    MOV BX, 0FFh
	    
	    CALL DELAY_1MS
	    
	RET
		  
	DELAY2:
	    MOV BX, 0FFF5h
	    
	    CALL DELAY_1MS
		  
	 RET
	 
	 DELAY_RELAY:
	    MOV BX, 0FFF1h
	    
	    CALL DELAY_1MS
		  
	 RET
	 
	 DELAY_KEYPAD:
	    MOV BX, 05000h
	    
	    CALL DELAY_1MS
		  
	 RET
	 
	 DELAY_1MS:
	       MOV DX, PORTA3
	       MOV AL, 0CFH
	       OUT DX, AL
	       
	       MOV AL, 07H
	       OUT DX, AL
	       
	       DEC BX
	       JNZ DELAY_1MS
	 RET
	
	INIT_LCD:
	    MOV AL, 38h
	    CALL INST_CTRL
	    
	    MOV AL, 08h
	    CALL INST_CTRL
	    
	    MOV AL, 01h
	    CALL INST_CTRL
	    
	    MOV AL, 06h
	    CALL INST_CTRL
	    
	    MOV AL, 0Ch
	    CALL INST_CTRL
	    
	RET
	
	INST_CTRL:
	    PUSH AX
	    
	    MOV DX, PORTA
	    OUT DX, AL
	    
	    MOV DX, PORTB
	    MOV AL, 02h
	    OUT DX, AL
	    
	    CALL DELAY1
	    
	    MOV DX, PORTB
	    MOV AL, 00h
	    
	    OUT DX, AL
	    POP AX
	    
	RET
	
	DATA_CTRL:
	    PUSH AX
	    
	    MOV DX, PORTA
	    OUT DX, AL
	    
	    MOV DX, PORTB
	    MOV AL, 03h
	    OUT DX, AL
	    
	    CALL DELAY1
	    
	    MOV DX, PORTB
	    MOV AL, 01h
	    OUT DX, AL
	    
	    POP AX
	    
	 RET
	 
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START
